### ISSUE TITLE
Where is the mask?

### ISSUE THREAD

**Issue by aleksandereiken** [zuruoke/watermark-removal#1]
Hi,
The script is failing in line 31 of the main.py
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    assert image.shape == mask.shape
AttributeError: 'NoneType' object has no attribute 'shape'

Looks like there is no folder file "mask.png" in the github repo?

**Comment by zuruoke** [comment]
fixed!! let me know when it's working for you

P.S: preferable use istock pics of 683 x 1024 or aspect ratio 1.4 to get better results

**Comment by dfmjndm** [comment]
> fixed!! let me know when it's working for you
> 
> P.S: preferable use istock pics of 683 x 1024 or aspect ratio 1.4 to get better results

Sorry, I have the same problem in the new version
--------------------------------------------------------------------------------
image size: (1000, 706, 3)
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    input_image = preprocess_image(image, args.watermark_type)
  File "G:\watermark-removal\preprocess_image.py", line 25, in preprocess_image
    "utils/{}/{}/mask.png".format(watermark_type, image_type))
  File "D:\Python37\lib\site-packages\PIL\Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/istock/potrait/mask.png'

**Comment by Prem95** [comment]
Just change the path to an absolute path directing to your mask.png

**Comment by dfmjndm** [comment]
> Just change the path to an absolute path directing to your mask.png

So where can i find the mask?It doesn't exist in the repository.

**Comment by Prem95** [comment]
It’s under utils/istock/landscape. Please check through the repo throughly.

**Comment by dfmjndm** [comment]
thanks
