### ISSUE TITLE
Missing potrait/mask.png

### ISSUE THREAD

**Issue by Marc-3d** [zuruoke/watermark-removal#4]
Hi zuruoke, 

That's a great tool you are putting out there. I have run the command all the commands, your package seems to detect that I want to clean up a portrait and is looking for "utils/portrait/mask.png", but the "portrait" folder does not even exist. 

Here is the error message: 

```
image size: (1730, 1155, 3)
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    input_image = preprocess_image(image, args.watermark_type)
  File "/content/watermark-removal/preprocess_image.py", line 25, in preprocess_image
    "utils/{}/{}/mask.png".format(watermark_type, image_type))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'utils/istock/potrait/mask.png'
```
Should I run some code to generate the mask?

**Comment by Prem95** [comment]
Just change the path in the file to the absolute path. It will work.
