### ISSUE TITLE
Image size not supported!!!

### ISSUE THREAD

**Issue by hallejuyahaha** [zuruoke/watermark-removal#8]
What are the requirements of the program for the size of the picture

**Comment by zuruoke** [comment]
@hallejuyahaha please this is not an issue, kindly create a discussion on this topic

**Comment by zuruoke** [comment]
and the requirement is 1024 x 683 or an aspect ratio between 1.25 and 1.6 recommended

**Comment by lihuismile79** [comment]
How to modifty the codes to fit other image sizes?
